contakto/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('app.front.urls')),

    url(r'^api/', include('app.api.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

app/entrevista/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from app.investigacion.models import Investigacion

ACTIVO_OPCIONES = (
	    (1, 'Sí'),
	    (2, 'No'),
	)

class EntrevistaFile(models.Model):
	record = models.FileField(verbose_name='Archivo', upload_to='xls')
	fecha_registro = models.DateField(auto_now=True)

	def __unicode__(self):
		return u'%s' % self.record

class EntrevistaPersona(models.Model):
	investigacion = models.ForeignKey(Investigacion)
	nombre = models.CharField(max_length=140)
	nss = models.CharField(verbose_name='NSS (IMSS)', max_length=30, blank=True, null=True)
	edad = models.CharField(max_length=140, blank=True, null=True)
	curp = models.CharField(verbose_name='CURP', max_length=30, blank=True, null=True)
	rfc = models.CharField(verbose_name='RFC', max_length=30, blank=True, null=True)
	ife = models.CharField(verbose_name='Folio credencial IFE', max_length=30, blank=True, null=True)
	pasaporte = models.CharField(verbose_name='No. de pasaporte o visa', max_length=30, blank=True, null=True)
	smn = models.CharField(verbose_name='Cartilla SMN', max_length=30, blank=True, null=True)
	estado_civil = models.CharField( max_length=100, verbose_name='Estado civil', blank=True, null=True)
	fecha_matrimonio = models.CharField(verbose_name='Fecha de matrimonio', max_length=100, blank=True, null=True)
	religion = models.CharField(verbose_name='Religión', max_length=140)
	tiempo_radicando = models.CharField(verbose_name='Tiempo radicando en la ciudad', max_length=140, blank=True, null=True)
	medio_utilizado = models.CharField(verbose_name='Medio que utiliza para transporte', max_length=140, blank=True, null=True)
	fecha_registro = models.DateField(auto_now=True)
	activa = models.BooleanField(default=True)
	dependientes_economicos = models.TextField(max_length=200, blank=True, null=True)

	def __unicode__(self):
		return u'%s / %s' % (self.id, self.nombre)

class EntrevistaInvestigacion(models.Model):
	RESULTADO_OPCIONES = (
		('0', 'Por evaluar'),
	    ('1', 'Viable'),
	    ('2', 'Con reservas'),
	    ('3', 'No viable'),
	)
	agente = models.ForeignKey(User)
	persona = models.ForeignKey(EntrevistaPersona)
	empresa_contratante = models.CharField(max_length=140, blank=True, null=True) #models.ForeignKey(Compania, null=True, blank=True)
	fecha_recibido = models.CharField(max_length=140, blank=True, null=True) #Del excel
	puesto = models.CharField(max_length=140, blank=True, null=True)
	fecha_registro = models.CharField(max_length=140, blank=True, null=True)
	conclusiones = models.TextField() # NOTA: posiblemente se puede borrar
	resultado = models.CharField(max_length=30, choices=RESULTADO_OPCIONES, blank=True, null=True)
	archivo = models.ForeignKey(EntrevistaFile, blank=True, null=True)
	folio = models.CharField(max_length=50, blank=True, null=True)
	presupuesto = models.CharField(max_length=50, blank=True, null=True)	

	def __unicode__(self):
		return u'%s / %s' % (self.persona, self.archivo)

'''
	Cita
'''
class EntrevistaCita(models.Model):
	investigacion = models.ForeignKey(Investigacion)
	fecha_entrevista = models.DateField(blank=True, null=True)
	hora_entrevista = models.TimeField(blank=True, null=True)
	entrevistador = models.CharField(max_length=200, blank=True, null=True)
	autorizada = models.IntegerField(default=0, choices=ACTIVO_OPCIONES, blank=True, null=True)
	observaciones = models.TextField(max_length=500, null=True, blank=True)

	def __unicode__(self):
		return u'%s' % (self.investigacion)

'''
	Modelos Datos Generales 
'''
class EntrevistaTelefono(models.Model):
	TELEFONO_OPCIONES = (
	    ('casa', 'casa'),
	    ('movil', 'movil'),
	    ('otro', 'otro'),
	    ('recado', 'recado'),
	)
	persona = models.ForeignKey(EntrevistaPersona)
	categoria = models.CharField(max_length=20, choices=TELEFONO_OPCIONES)
	numero = models.CharField(max_length=20, null=True, blank=True)
	parentesco = models.CharField(max_length=40, blank=True, null=True)

	def __unicode__(self):
		return self.numero

class EntrevistaDireccion(models.Model):
	persona = models.ForeignKey(EntrevistaPersona)
	calle = models.CharField(verbose_name='Calle / Num ext-int', max_length=140, null=True, blank=True)
	ciudad = models.CharField(verbose_name='Ciudad', max_length=140, null=True, blank=True)
	colonia = models.CharField(verbose_name='Colonia o fraccionamiento', max_length=140, null=True, blank=True)
	cp = models.CharField(verbose_name='Código Postal', max_length=140, null=True, blank=True)
	estado = models.CharField(verbose_name='Estado', max_length=140, null=True, blank=True)

	def __unicode__(self):
		return '%s, %s, %s' % (self.calle, self.colonia, self.ciudad)

class EntrevistaPrestacionVivienda(models.Model):
	VIVIENDA_OPCIONES = (
	    ('infonavit', 'infonavit'),
	    ('fonacot', 'fonacot'),
	)
	persona = models.ForeignKey(EntrevistaPersona)
	categoria_viv = models.CharField(max_length=20, choices=VIVIENDA_OPCIONES)
	activo = models.CharField(verbose_name='Tiene crédito activo', max_length=140, null=True, blank=True)
	fecha_tramite = models.CharField(verbose_name='Fecha en que fue tramitado', max_length=140, null=True, blank=True)
	numero_credito = models.CharField(verbose_name='No. de crédito', max_length=140, null=True, blank=True)
	uso = models.CharField(max_length=250, null=True, blank=True)

	def __unicode__(self):
		return self.categoria_viv

class EntrevistaLicencia(models.Model):
	persona = models.ForeignKey(EntrevistaPersona)
	numero = models.CharField(verbose_name='No. de licencia', max_length=20, null=True, blank=True)
	tipo = models.CharField(verbose_name='Tipo de licencia', max_length=14, null=True, blank=True)
	
	def __unicode__(self):
		return '%s, %s' % (self.tipo, self.numero)

class EntrevistaOrigen(models.Model):
	persona = models.ForeignKey(EntrevistaPersona)
	lugar = models.CharField(verbose_name='Lugar de nacimiento', max_length=140, null=True, blank=True)
	nacionalidad = models.CharField(max_length=140, null=True, blank=True)
	fecha = models.CharField(verbose_name='Fecha de nacimiento', max_length=140, null=True, blank=True)

	def __unicode__(self):
		return '%s, %s' % (self.lugar, self.fecha)


'''
	Modelos Info Personal
'''
class EntrevistaInfoPersonal(models.Model):
	persona = models.ForeignKey(EntrevistaPersona)
	objetivo_personal = models.CharField(verbose_name='Objetivo personal', max_length=500)
	objetivo_en_empresa = models.CharField(verbose_name='Objetivo en la empresa', max_length=500, null=True, blank=True)
	cualidades = models.CharField(max_length=500, null=True, blank=True)
	defectos = models.CharField(max_length=500, null=True, blank=True)
	trabajo_que_desarrolla = models.CharField(verbose_name='Tipo de trabajo que le gusta desarrollar', max_length=500, null=True, blank=True)
	antecedentes_penales = models.CharField(verbose_name='Demandas Laborales y/o Antecedentes Penales', max_length=500, null=True, blank=True)
	tatuajes = models.CharField(verbose_name='Cuenta con algún tatuaje o arete:(Cuantos y en que parte del cuerpo)', max_length=500, null=True, blank=True)

	def __unicode__(self):
		return  '%s,%s' % (self.objetivo_personal, self.objetivo_en_empresa)


class EntrevistaHistorialEnEmpresa(models.Model):
	HISTORIAL_OPCIONES = (
	    ('trabajo', 'trabajo'),
	    ('familiar', 'familiar'),
	)
	persona = models.ForeignKey(EntrevistaPersona)
	categoria = models.CharField(max_length=20, choices=HISTORIAL_OPCIONES)
	tiene = models.CharField(max_length=140, null=True, blank=True)
	puesto = models.CharField(max_length=500, null=True, blank=True)
	periodo = models.CharField(max_length=500, null=True, blank=True)	#Solo para categ. trabajo
	nombre = models.CharField(max_length=140, null=True, blank=True)	#Solo para cate. familiar

	def __unicode__(self):
		return '%s, %s' % (self.categoria, self.puesto)
	

'''
	Modelos Salud/ActividadesHabitos
'''

class EntrevistaSalud(models.Model):
	persona = models.ForeignKey(EntrevistaPersona)
	peso_kg = models.CharField(max_length=200, null=True, blank=True)
	estatura_mts = models.CharField(max_length=200, null=True, blank=True)
	salud_fisica = models.CharField(max_length=200, null=True, blank=True)
	salud_visual = models.CharField(max_length=200, null=True, blank=True)
	embarazo_meses = models.CharField(max_length=200, null=True, blank=True)
	ejercicio_tipo_frecuencia = models.CharField(max_length=200, null=True, blank=True)
	accidentes = models.CharField(max_length=200, null=True, blank=True)
	intervenciones_quirurgicas = models.CharField(max_length=200, null=True, blank=True)
	enfermedades_familiares = models.CharField(max_length=200, null=True, blank=True)
	tratamiento_medico_psicologico = models.CharField(max_length=200, null=True, blank=True)
	enfermedades_mayor_frecuencia = models.CharField(max_length=200, null=True, blank=True)
	institucion_medica = models.CharField(max_length=200, null=True, blank=True)

	def __unicode__(self):
		return '%s, %s' % (self.enfermedades_mayor_frecuencia, self.enfermedades_familiares)

class EntrevistaActividadesHabitos(models.Model):
	persona = models.ForeignKey(EntrevistaPersona)
	tiempo_libre = models.CharField(max_length=140, null=True, blank=True)
	extras = models.CharField(max_length=140, null=True, blank=True)
	frecuencia_tabaco = models.CharField(max_length=140, null=True, blank=True)
	frecuencia_alcohol = models.CharField(max_length=140, null=True, blank=True)
	frecuencia_otras_sust = models.CharField(max_length=140, null=True, blank=True)

	def __unicode__(self):
		return '%s' % (self.tiempo_libre)

'''
	Modelos información Académica
'''

class EntrevistaAcademica(models.Model):
	person = models.ForeignKey(EntrevistaPersona)
	cedula_profesional = models.CharField(max_length=200, null=True, blank=True)
	cedula_prof_ano_exp = models.CharField(max_length=200, null=True, blank=True)
	estudios_actuales = models.CharField(max_length=200, null=True, blank=True)
	
	def __unicode__(self):
		return '%s' % (self.estudios_actuales)

resources/templates/mint/sections/entrevista/forms/academica_form.html
{% load fe_extras %}
<form action="#" method="post">{% csrf_token %}
	{% if request.user.is_staff %}	
		<div class="row">
			<div class="col-md-2 col-md-offset-10">
				<button class="btn btn-lrg btn-primary" type="submit">Guardar cambios <span class="glyphicon glyphicon-save"></span></button>
			</div>
		</div>
	{% endif %}
	{{ gradosescolaridad_formset.management_form }}
	<div class="row">
		<div class="col-xs-1 text-center"><label><small>ESCOLARIDAD</small></label></div>
		<div class="col-xs-5 text-center"><label><small>INSTITUCIÓN</small></label></div>
		<div class="col-xs-2 text-center"><label><small>LUGAR (CIUDAD)</small></label></div>
		<div class="col-xs-2 text-center"><label><small>AÑOS</small></label></div>
		<div class="col-xs-2 text-center"><label><small>CERTIFICADO</small></label></div>
	</div>
	<div class="row">
		<div class="col-xs-10">
			<hr class="thin-separator" />
		</div>
	</div>
	{% for form in gradosescolaridad_formset %}
		{{ form.id }}
		<div class="row">
			<div class="col-xs-1">
				<label><small>{{ form.instance.grado|entrevista_grado_academico }}:</small></label>
			</div>
			<div class="col-xs-5">
				<div class="text-danger">
					{{form.institucion.errors}}
				</div>
				{{form.institucion}}
			</div>
			<div class="col-xs-2">
				<div class="text-danger">
					{{form.ciudad.errors}}
				</div>
				{{form.ciudad}}
			</div>
			<div class="col-xs-2">
				<div class="text-danger">
					{{form.anos.errors}}
				</div>
				{{form.anos}}
			</div>
			<div class="col-xs-2">
				<div class="text-danger">
					{{form.certificado.errors}}
				</div>
				{{form.certificado}}
			</div>
		</div>
		<div class="row">
			<div class="col-xs-10">
				<hr class="thin-separator" />
			</div>
		</div>
	{% endfor %}

	<br />
	<div class="row">
		<div class="col-xs-3">
			<div class="text-danger">{{ otro_idioma_form.idioma.errors }}</div>
			<label>Dominio de otro idioma:</label>
			{{ otro_idioma_form.idioma }}
		</div>
		<div class="col-xs-3">
			<div class="text-danger">{{ otro_idioma_form.porcentaje.errors }}</div>
			<label>Porcentaje:</label>
			{{ otro_idioma_form.porcentaje }}
		</div>
		<div class="col-xs-3">
			<div class="text-danger">{{ academica_form.cedula_profesional.errors }}</div>
			<label>Cédula profesional:</label>
			{{ academica_form.cedula_profesional }}
		</div>
		<div class="col-xs-3">
			<div class="text-danger">{{ academica_form.cedula_prof_ano_exp.errors }}</div>
			<label>Año de expedición:</label>
			{{ academica_form.cedula_prof_ano_exp }}
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12">
			<div class="text-danger">{{ academica_form.estudios_actuales.errors }}</div>
			<label>Estudia actualmente (institución, qué estudia, horarios, días):</label>
			{{ academica_form.estudios_actuales }}
		</div>
	</div>
</form>

resources/templates/mint/sections/entrevista/forms/cita_form.html
<form action="#" method="post">{% csrf_token %}
	<div class="row">
		<div class="col-md-2 col-md-offset-10">
			<button class="btn btn-lrg btn-primary" type="submit">Guardar cambios <span class="glyphicon glyphicon-save"></span></button>
		</div>
	</div>
	<br />
	<div class="row">
		<div class="col-md-3">
			<div class="form-group">
				<div class="text-danger">{{cita_form.autorizada.errors}}</div>
				{{cita_form.autorizada.label_tag}}
				{{cita_form.autorizada}}
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4">
			<div class="form-group">
				<div class="text-danger">{{cita_form.entrevistador.errors}}</div>
				{{cita_form.entrevistador.label_tag}}
				{{cita_form.entrevistador}}
			</div>
		</div>
		<div class="col-md-4">
			<div class="row">
				<div class="col-md-6">
					<label for="id_fecha_entrevista">Fecha:</label>
				</div>
				<div class="col-md-6">
					<label for="id_fecha_entrevista">Hora:</label>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<div class="text-danger">{{cita_form.fecha_entrevista.errors}}</div>
						<!-- {{cita_form.fecha_entrevista.label_tag}} -->
						{{cita_form.fecha_entrevista}}
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<div class="text-danger">{{cita_form.hora_entrevista.errors}}</div>
						<!-- {{cita_form.hora_entrevista.label_tag}} -->
					
						{{cita_form.hora_entrevista}}

					</div>
				</div>
			</div>
		</div>
	</div>
	

resources/templates/mint/sections/entrevista/forms/datos_grales_form.html
<form action="#" method="post">{% csrf_token %}
	<div>


		<div class="row">
			<div class="col-md-3">
				<div class="text-danger">{{ candidato_form.nombre.errors }}</div>
				{{ candidato_form.nombre.label_tag }}
				{{ candidato_form.nombre }}
			</div>

			{% if request.user.is_staff %}
				<div class="col-md-2 col-md-offset-8">
					<button class="btn btn-lrg btn-primary" type="submit">Guardar cambios <span class="glyphicon glyphicon-save"></span></button>
				</div>
			{% endif %}

		</div>

		<div class="row">
			<div class="col-md-2">
				<h5><strong>DOMICILIO</strong></h5>
			</div>
		</div>

		<div class="row">
			<div class="col-md-3">
				<div class="text-danger">{{ direccion_form.calle.errors }}</div>
				{{ direccion_form.calle.label_tag }}
				{{ direccion_form.calle }}
			</div>
			<div class="col-md-3">
				<div class="text-danger">{{ direccion_form.colonia.errors }}</div>
				{{ direccion_form.colonia.label_tag }}
				{{ direccion_form.colonia }}
			</div>

			<div class="col-md-2">
				<div class="text-danger">{{ direccion_form.ciudad.errors }}</div>
				{{ direccion_form.ciudad.label_tag }}
				{{ direccion_form.ciudad }}
			</div>
			<div class="col-md-2">
				<div class="text-danger">{{ direccion_form.estado.errors }}</div>
				{{ direccion_form.estado.label_tag }}
				{{ direccion_form.estado }}
			</div>
			<div class="col-md-2">
				<div class="text-danger">{{ direccion_form.cp.errors }}</div>
				{{ direccion_form.cp.label_tag }}
				{{ direccion_form.cp }}
			</div>		
		</div>
		<hr class="thin-separator" />
		<div class="row">
			<div class="col-md-2">
				<h5><strong>TELÉFONOS</strong></h5>
			</div>
		</div>
		<div class="row">
			{{ tel_formset.management_form }}
				{% for form in tel_formset %}
					<div class="col-md-3">
						<h5>{{ form.instance.categoria|title }}</h5>
						{{ form.id }}
						<div class="text-danger">
							{{form.numero.errors}}
						</div>
						<label>Número:</label>
						{{form.numero}}
						{% if form.instance.categoria == 'recado' or form.instance.categoria == 'otro' %}
						<div class="text-danger">
							{{form.parentesco.errors}}
						</div>
						<label>Parentesco:</label>
						{{form.parentesco}}
						{% endif %}
					</div>
				{% endfor %}
		</div>

		<hr class="thin-separator" />
		<div class="row">
			<div class="col-md-4">
				<div class="text-danger">{{ origen_form.lugar.errors }}</div>
				{{ origen_form.lugar.label_tag }}
				{{ origen_form.lugar }}
			</div>
			<div class="col-md-4">
				<div class="text-danger">{{ origen_form.fecha.errors }}</div>
				{{ origen_form.fecha.label_tag }}
				{{ origen_form.fecha }}
			</div>
			<div class="col-md-4">
				<div class="text-danger">{{ origen_form.nacionalidad.errors }}</div>
				{{ origen_form.nacionalidad.label_tag }}
				{{ origen_form.nacionalidad }}
			</div>
		</div>
		
		<div class="row">
			<div class="col-md-3">
				<div class="text-danger">{{ candidato_form.rfc.errors }}</div>
				{{ candidato_form.rfc.label_tag }}
				{{ candidato_form.rfc }}
			</div>
			<div class="col-md-3">
				<div class="text-danger">{{ candidato_form.curp.errors }}</div>
				{{ candidato_form.curp.label_tag }}
				{{ candidato_form.curp }}
			</div>
			<div class="col-md-3">
				<div class="text-danger">{{ candidato_form.ife.errors }}</div>
				{{ candidato_form.ife.label_tag }}
				{{ candidato_form.ife }}
			</div>
			<div class="col-md-3">
				<div class="text-danger">{{ candidato_form.smn.errors }}</div>
				{{ candidato_form.smn.label_tag }}
				{{ candidato_form.smn }}
			</div>
		</div>

		<div class="row">
			<div class="col-md-3">
				<div class="text-danger">{{ licencia_form.tipo.errors }}</div>
				{{ licencia_form.tipo.label_tag }}
				{{ licencia_form.tipo }}
			</div>
			<div class="col-md-3">
				<div class="text-danger">{{ licencia_form.numero.errors }}</div>
				{{ licencia_form.numero.label_tag }}
				{{ licencia_form.numero }}
			</div>
			<div class="col-md-6">
				<div class="text-danger">{{ candidato_form.pasaporte.errors }}</div>
				{{ candidato_form.pasaporte.label_tag }}
				{{ candidato_form.pasaporte }}
			</div>
		</div>

		<div class="row">
			<div class="col-md-3">
				<div class="text-danger">{{ candidato_form.nss.errors }}</div>
				{{ candidato_form.nss.label_tag }}
				{{ candidato_form.nss }}
			</div>
			<div class="col-md-3">
				<div class="text-danger">{{ candidato_form.estado_civil.errors }}</div>
				{{ candidato_form.estado_civil.label_tag }}
				{{ candidato_form.estado_civil }}
			</div>
			<div class="col-md-3">
				<div class="text-danger">{{ candidato_form.fecha_matrimonio.errors }}</div>
				{{ candidato_form.fecha_matrimonio.label_tag }}
				{{ candidato_form.fecha_matrimonio }}
			</div>
			<div class="col-md-3">
				<div class="text-danger">{{ candidato_form.religion.errors }}</div>
				{{ candidato_form.religion.label_tag }}
				{{ candidato_form.religion }}
			</div>
		</div>

		<div class="row">
			<div class="col-md-6">
				<div class="text-danger">{{ candidato_form.tiempo_radicando.errors }}</div>
				{{ candidato_form.tiempo_radicando.label_tag }}
				{{ candidato_form.tiempo_radicando }}
			</div>
			<div class="col-md-6">
				<div class="text-danger">{{ candidato_form.medio_utilizado.errors }}</div>
				{{ candidato_form.medio_utilizado.label_tag }}
				{{ candidato_form.medio_utilizado }}
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				<div class="text-danger">{{ candidato_form.dependientes_economicos.errors }}</div>
				{{ candidato_form.dependientes_economicos.label_tag }}
				{{ candidato_form.dependientes_economicos }}
			</div>
		</div>

		<hr />
		{{ pv_formset.management_form }}
		{% for form in pv_formset %}
			{{ form.id }}
			<div class="row">
				<div class="col-md-2">
					<h4>{{ form.instance.categoria_viv|title }}</h4>
				</div>	
				<div class="col-md-2">
					<div class="text-danger">{{ form.activo.errors }}</div>
					{{ form.activo.label_tag }}
					{{ form.activo }}
				</div>
				<div class="col-md-2">
					<div class="text-danger">{{ form.numero_credito.errors }}</div>
					{{ form.numero_credito.label_tag }}
					{{ form.numero_credito }}
				</div>
				<div class="col-md-2">
					<div class="text-danger">{{ form.fecha_tramite.errors }}</div>
					{{ form.fecha_tramite.label_tag }}
					{{ form.fecha_tramite }}
				</div>
				<div class="col-md-4">
					<div class="text-danger">{{ form.uso.errors }}</div>
					{{ form.uso.label_tag }}
					{{ form.uso }}
				</div>
			</div>
			{% if not forloop.last %}
			<hr class="thin-separator" />
			{% endif %}
		{% endfor %}
	
	</div>
</form>

resources/templates/mint/sections/entrevista/forms/evaluacion_form.html
{% load fe_extras %}
<form action="#" method="post">{% csrf_token %}
	{% if request.user.is_staff %}
		<div class="row">
			<div class="col-md-2 col-md-offset-10">
				<button class="btn btn-lrg btn-primary" type="submit">Guardar cambios <span class="glyphicon glyphicon-save"></span></button>
			</div>
		</div>
	{% endif %}
	<div class="row">
		<div class="col-xs-6">
			{{ documentos_formset.management_form }}
			<h2>Documentos evaluados</h2>

			{% for form in documentos_formset %}
				{{ form.id }}
				{% if form.instance.tipo == 'motivos_falta_docs' %}
				<br />
				{% endif %}
				<div class="row">
					
						{% if form.instance.tipo == 'motivos_falta_docs' %}
						<div class="col-xs-12" >
							<label>{{form.instance.tipo|clean_type}}:</label>
							<div class="text-danger">{{ form.observaciones.errors }}</div>
							{{form.observaciones}}
						</div>
						{% else %}
						<div class="col-xs-8">
							<label>{{form.instance.tipo|clean_type}}:</label>
						</div>
						<div class="col-xs-4">
							<div class="text-danger">{{ form.estatus.errors }}</div>
							{{form.estatus}}
						</div>
							
						{% endif %}
				</div>
				{% if not forloop.last %}
					<hr  class="thin-separator" />
				{% endif %}
			{% endfor %}
		</div>
		<div class="col-xs-5 col-xs-offset-1">
			{{ aspectos_hogar_formset.management_form }}
			<h2>Calificación de 1% a 100%</h2>
			<h4>Aspecto del hogar:</h4>
			{% for form in aspectos_hogar_formset %}
				{{ form.id }}
				<div class="row">
					<div class="col-xs-7" >
						<label>{{form.instance.tipo|clean_type}}:</label>
					</div>
					<div class="col-xs-5">
						<div class="text-danger">{{ form.estatus.errors }}</div>
						{{form.estatus}}
					</div>
				</div>
				<hr  class="thin-separator" />	
			{% endfor %}
			<br />
			{{ aspectos_candidato_formset.management_form }}
			<h4>Aspecto del candidato:</h4>
			{% for form in aspectos_candidato_formset %}
				{{ form.id }}
				<div class="row">
					<div class="col-xs-7" >
						<label>{{form.instance.tipo|clean_type}}:</label>
					</div>
					<div class="col-xs-5">
						<div class="text-danger">{{ form.estatus.errors }}</div>
						{{form.estatus}}
					</div>
				</div>
				<hr  class="thin-separator" />	
			{% endfor %}
		</div>
	</div>
	<br />
	<hr />
	{{investigacion_form.errors}}
	<div class="row">
		<div class="col-md-6">
			<div class="form-group">
				<div class="text-danger">{{investigacion_form.resultado.errors}}</div>
				<label>Resultado de la entrevista:</label>
				{{investigacion_form.resultado}}
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<div class="text-danger">{{investigacion_form.conclusiones.errors}}</div>
				<label>Conclusiones de la entrevista:</label>
				{{investigacion_form.conclusiones}}
			</div>
		</div>
		
	</div>
</form>